### ISSUE TITLE
...Nothing happens

### ISSUE THREAD

**Issue by element4l** [akosbalasko/yarle#232] opened 2021-04-05 22:19 UTC
Hi, so I set this all up, but when I press start, nothing happens for a while, unlessI press the button a couple of times, and eventually it spits out this in the log, but nothing ever comes out of the destination folder. I am using the newest version with the UI:

path: C:\Users\Username\Downloads\Evernote.enex
config: true
config: true
config: true
config: true
config: true
config: true
config: true
config: "_"
config: "/"
config: "-"
template and config: "{title-block}# {title}{end-title-block}\n---\n{tags-block}\nTagged: \n```\n{tags}\n```\n{end-tags-block}\n---\n{content-block}{content}{end-content-block}\n---\n{created-at-block}   Created at: {created-at}._{end-created-at-block}\n{updated-at-block}   Updated at: {updated-at}._{end-updated-at-block}\n{source-url-block}   Source URL: []({source-url})._{end-source-url-block}\n\n\n"
config: false
config: false

I have Node.js v13.14 on Windows 7. Though I noticed something happened that chocolatey did not install properly. I don't know if that's related. 

I've tried this on multiple different enex files.

**Comment by akosbalasko** [comment] 2021-04-06 06:00
Hi @element4l !
I'm trying to reproduce the issue, but until then let me have a question: From which Evernote version did you export your notes?

**Comment by element4l** [comment] 2021-04-06 14:23
Evernote legacy 6.25.2

**Comment by seatrout** [comment] 2021-04-07 09:04
I have the same issue, also with `.enex` generated by EN 6.25

**Comment by seatrout** [comment] 2021-04-07 09:13
Is it possible to revert to the old NPX method and still have the fixes in the latest update?

**Comment by akosbalasko** [comment] 2021-04-07 11:02
Hi @seatrout , @element4l ,
It looks like that the conversion is not triggered by the UI on Windows only. Sorry for the problems, I investigate it further and provide a solution asap. 
@seatrout yes, it's possible, npx command is supported.

**Comment by oldenough** [comment] 2021-04-08 13:21
I'm wondering if this might not be my problem as well.  I posted about it over on [the discussion board](https://github.com/akosbalasko/yarle/discussions/236).  I am using a version of Yarle that I downloaded from GitHub yesterday and the Evernote version is 10+.  No matter what I do I get no log output, and it does seem like electron(?) is capturing my entries, but when I hit convert it feels like absolutely noting happens.

**Comment by akosbalasko** [comment] 2021-04-08 18:34
Hi @seatrout @oldenough @element4l ,

It's fixed in release 4.0.3, please download the fresh binary from here: https://github.com/akosbalasko/yarle/releases/download/v4.0.3/yarle-evernote-to-md-4.0.3.Setup.exe

And of course, feel free to open a new issue, if you face with any problems. 

Cheers,

**Closed by akosbalasko** 2021-04-08 18:34 UTC
