### ISSUE TITLE
Node fails without log on Dates prior to Epoch time

### ISSUE THREAD

**Issue by montemartin** [akosbalasko/yarle#362] opened 2022-03-09 02:01 UTC
Not sure how it happened but one of my notes ended up with a date from 1969 - `<created>19691210T183646Z</created>`. When I tried to process my notes through YARLE desktop app it would hang indefinitely. I finally decided to use the CLI and got the following error:

```
/Users/monte/.npm/_npx/106a035a6ccf201d/node_modules/utimes/src/utimes/index.js:200
		throw new Error(key + ' must be a positive integer');
		      ^

Error: btime must be a positive integer
    at assertTime (/Users/monte/.npm/_npx/106a035a6ccf201d/node_modules/utimes/src/utimes/index.js:200:9)
    at getFullOptions (/Users/monte/.npm/_npx/106a035a6ccf201d/node_modules/utimes/src/utimes/index.js:117:2)
    at Object.utimes (/Users/monte/.npm/_npx/106a035a6ccf201d/node_modules/utimes/src/utimes/index.js:27:16)
    at Object.setFileDates (/Users/monte/.npm/_npx/106a035a6ccf201d/node_modules/yarle-evernote-to-md/dist/utils/content-utils.js:121:18)
    at Object.writeFile (/Users/monte/.npm/_npx/106a035a6ccf201d/node_modules/yarle-evernote-to-md/dist/utils/file-utils.js:29:25)
    at Object.saveMdFile (/Users/monte/.npm/_npx/106a035a6ccf201d/node_modules/yarle-evernote-to-md/dist/utils/save-md-file.js:9:18)
    at Object.processNode (/Users/monte/.npm/_npx/106a035a6ccf201d/node_modules/yarle-evernote-to-md/dist/process-node.js:41:17)
    at EventEmitter.<anonymous> (/Users/monte/.npm/_npx/106a035a6ccf201d/node_modules/yarle-evernote-to-md/dist/yarle.js:116:32)
    at EventEmitter.emit (node:events:376:20)
    at SAXStream.<anonymous> (/Users/monte/.npm/_npx/106a035a6ccf201d/node_modules/xml-flow/lib/xml-flow.js:142:15)
```

It took a lot of searching to get from that error to what the actual issue was, and which note was causing the problem. The challenge was the output to the conversion.log ended with the previously processed note, no mention of further errors.

The bug is probably fixable, but this case is probably rare so it might be more helpful to improve error reporting when Node runs into an issue. I would expect the conversion log to include the error message and at least the name of the note causing the issue.

**Comment by akosbalasko** [comment] 2022-03-11 21:54
Fixed in version 4.8.5

**Closed by akosbalasko** 2022-03-11 21:54 UTC
Labels: bug, enhancement

**Comment by duanemay** [comment] 2022-04-03 17:49
I am seeing the same issue "Error: btime must be a positive integer" and am running with version 4.8.5.

I am still trying to find what the issue is, as @montemartin noted: The challenge was the output to the conversion.log ended with the previously processed note, no mention of further errors.

**Comment by montemartin** [comment] 2022-04-04 16:02
@duanemay In my case it was an incorrect date. Take a look (in  your .enml) at the `<created>` tag for the note right after the last one that processed successfully.
