### ISSUE TITLE
tags rendered as #//// #////// #//

### ISSUE THREAD

**Issue by filmgal** [akosbalasko/yarle#376] opened 2022-05-03 21:46 UTC
Yarle worked fine for me in February, but I had to reinstall today and now all of my tags get rendered as follows:

![image](https://user-images.githubusercontent.com/30246308/166571133-7db4fc52-a453-4c82-8578-2e351f5334b4.png)

The only "tag" option I have enabled is "Add # to tag".
Some of my Evernote tags have "."s in them, i.e, `p.this` or `p.that`, but most do not.  My first attempt was to enable the conversion of "." to "/" and got the tags looking like the picture, so I disabled that option and got the same result. I uninstalled and re-installed, and still the same.

**Comment by akosbalasko** [comment] 2022-05-04 09:56
Hi @filmgal ,
Does it happens with the same enex file which was processed well in February? It's pretty strange, because I checked the changes and there were no changes around tags-generation. Could you please provide an example enex on what Yarle produces these //// characters? 

Thanks a lot!

**Comment by filmgal** [comment] 2022-05-04 16:01
Hi @[akosbalasko](https://github.com/akosbalasko)
Pretty sure the tags were fine in Feb. I'd show you an example but I lost my hard drive - hence repeating the Evernote exports!
Here's a small test file with just 3 files, to give you an idea.
[test.zip](https://github.com/akosbalasko/yarle/files/8622092/test.zip)

**Comment by filmgal** [comment] 2022-05-04 16:23
Perhaps it has something to do with the tags, in that some of them have "." separators (e.g., flare.settings) and some have hyphens ("flare-settings").

**Comment by akosbalasko** [comment] 2022-05-04 17:27
Hi @filmgal, 
thanks for the examples and for the hints, i'm on it.

**Comment by akosbalasko** [comment] 2022-05-04 19:55
Hi @filmgal ,
I was able to reproduce the problem, but only if I add '.' to the "Separator of the nested tag in EN" field, and '/' to its replacement. The tricky point is that I replace the characters by a regular expression in where the "." character is a joker character to mean anything, thats why all characters of the tag values were replaced by / sign. To escape this, please type "\." instead of ".", and it will work. I know, it's a workaround, but at least your notes will be converted until I find the correct solution. Here I attached how I set my nested tags-part:
<img width="509" alt="Screenshot 2022-05-04 at 21 50 14" src="https://user-images.githubusercontent.com/11886731/166815455-e8391852-3861-4aac-9977-395122e8254b.png">

**Comment by filmgal** [comment] 2022-05-04 20:11
Hi @akosbalasko 
Thank you SO much for the quick fix!  It works like a charm.  
You're the best.

**Comment by akosbalasko** [comment] 2022-05-05 09:14
Hi @filmgal ,
Cool, I'm glad that it works! 
I'd keep this issue open until I provide a proper solution, just to escape regexp-related fields automatically.

**Comment by akosbalasko** [comment] 2022-05-21 13:49
Hi @filmgal ,
Just fyi I released the fix in version 4.9.13, so I close this issue.

**Closed by akosbalasko** 2022-05-21 13:49 UTC
